### ISSUE TITLE
Update to oteapi-core v0.0.5

### ISSUE THREAD

**Issue by jesper-friis** [EMMC-ASBL/oteapi-plugin-template#24] opened 2022-02-08 20:20 UTC
Update example strategies, tests and setup.cfg to oteapi-core v0.0.5.

For setup.cfg, see also issue #23

**Comment by CasperWA** [comment] 2022-02-09 08:33
This has already been fixed by #20 and is a duplicate of #18.

**Closed by CasperWA** 2022-02-09 08:33 UTC
Labels: duplicate
